version: '3.8'

services:
  ipask:
    image: prestigen/ipask:latest
    hostname: ipask
    environment:
      - IPASK_PROD=true
      - GUNICORN_SERVER=    # default: ipask
      - GUNICORN_WORKERS=   # default: (cores * 2 + 1) if IPASK_PROD or 1
      - GUNICORN_THREADS=   # default: 1
      - GEOIP=false
      - REVERSE_DNS_LOOKUP=false
    restart: always

  nginx:
    image: nginx:latest
    hostname: ipask-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./resources/nginx.conf:/etc/nginx/nginx.conf:ro
      - $HOME/.nginx/cert.pem:/etc/nginx/cert.pem:ro
      - $HOME/.nginx/key.pem:/etc/nginx/key.pem:ro
    depends_on:
      - ipask
    restart: always
    logging:
      driver: none
