version: '3.8'

services:
  ipget:
    image: prestigen/ipget:latest
    hostname: ipget
    environment:
      - GUNICORN_SERVER=    # default: ipget
      - GUNICORN_BIND=      # default: "0.0.0.0:8080"
      - GUNICORN_WORKERS=   # default: cores * 2 + 1
      - GUNICORN_THREADS=   # default: 1
      - IP_API=false
    restart: always

  nginx:
    image: nginx:latest
    hostname: ipget-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./resources/nginx.conf:/etc/nginx/nginx.conf:ro
      - $HOME/.nginx/cert.pem:/etc/nginx/cert.pem:ro
      - $HOME/.nginx/key.pem:/etc/nginx/key.pem:ro
    depends_on:
      - ipget
    restart: always
    logging:
      driver: none
