version: '3.8'

services:
  ipget:
    image: prestigen/ipget:0.0.1
    hostname: ipget
    environment:
      - WORKERS=4
      - IP_API=false
      - FLASK_ENV=production
    restart: always

  nginx:
    image: nginx:latest
    hostname: ipget-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./resources/nginx.conf:/etc/nginx/nginx.conf:ro
      - $HOME/.nginx/cert.pem:/etc/nginx/cert.pem:ro
      - $HOME/.nginx/key.pem:/etc/nginx/key.pem:ro
    depends_on:
      - ipget
    restart: always
