name: Docker Build and Push

on:
  workflow_run:
    workflows: ["Python Lint and Test"]
    branches: ["master"]
    types: [completed]

env:
  IMAGE_NAME: "prestigen/ipask"

jobs:
  docker-build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the last git hash
        id: git
        run: |
          echo "IPASK_VERSION=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
        shell: bash

      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ steps.git.outputs.IPASK_VERSION }}
